apiVersion: apps/v1
kind: Deployment
metadata:
  name: alis-frontend
spec:
  selector:
    matchLabels:
      app: alis-frontend
  template:
    metadata:
      labels:
        app: alis-frontend
    spec:
      containers:
      - name: alis-frontend
        image: __DOCKER_TAG__
        env:
        - name: KEYCLOACK__REALM
          valueFrom:
            configMapKeyRef:
              name: alis-frontend-config
              key: keycloak__realm
        - name: KEYCLOACK__AUTH_SERVER_URL
          valueFrom:
            configMapKeyRef:
              name: alis-frontend-config
              key: keycloak__auth_server_url
        - name: KEYCLOACK__CLIENT_ID
          valueFrom:
            configMapKeyRef:
              name: alis-frontend-config
              key: keycloak__client_id
        - name: ALIS_BACKEND__SERVER_URL
          valueFrom:
            configMapKeyRef:
              name: alis-frontend-config
              key: alis_backend__server_url
        - name: LOGS_JSON_CONSOLE
          valueFrom: 
            configMapKeyRef: 
              name: alis-frontend-config
              key: logs_json_console
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "150m"
        ports:
        - containerPort: 80