services:
  frontend:
    image: ${DOCKER_IMAGE_NAME}
    container_name: 'frontend'
    environment:
      ALIS_BACKEND__SERVER_URL: '${EXTERNAL_IP_ADDRESS}/api/'
      KEYCLOACK__AUTH_SERVER_URL: '${EXTERNAL_IP_ADDRESS}/auth/'
      KEYCLOACK__CLIENT_ID: 'alis-front-client'
      KEYCLOACK__REALM: 'wmskorus'
      LOGS_JSON_CONSOLE: '1'
      WMS_BACKEND__SERVER_URL: 'http://185.149.50.37:55780/api/'
    restart: unless-stopped
    ports:
      - '80'
    networks:
      - web

  frontend_local:
    image: ${DOCKER_IMAGE_NAME}
    container_name: 'frontend_local'
    environment:
      ALIS_BACKEND__SERVER_URL: '${LOCAL_IP_ADDRESS}/api/'
      KEYCLOACK__AUTH_SERVER_URL: '${LOCAL_IP_ADDRESS}/auth/'
      KEYCLOACK__CLIENT_ID: 'alis-localfront-client'
      KEYCLOACK__REALM: 'wmskorus'
      LOGS_JSON_CONSOLE: '1'
      WMS_BACKEND__SERVER_URL: 'https://test-yard-exsim.alabuga.ru/api/'
    restart: unless-stopped
    ports:
      - '80'
    networks:
      - web


networks:
  web:
    external: true
